apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-service-template
  title: Quarkus Basic Service
  description: Generates a simple Quarkus service with a customizable package structure.
spec:
  owner: AgileIntegration
  type: service
  parameters:
    - title: Project Information
      properties:
        groupId:
          type: string
          description: The group ID for your project (e.g., net.gbm)
          default: "net.gbm"
        artifactId:
          type: string
          description: The artifact ID for your project
          default: "artifactId"
        version:
          type: string
          description: The version of your project (e.g., 1.0.0)
          default: "1.0.0"
        package:
          type: string
          description: The base Java package name (e.g., net.gbm)
          default: "net.gbm"
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-content
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/esebs/backstage-templates/tree/main/quarkus-template/skeleton
        values:
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          version: ${{ parameters.version }}
          package: ${{ parameters.package }}
          directory: ${{ parameters.package | replace('.', '/') }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}


